# Generated by Django 3.2.9 on 2021-11-24 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_add_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='total_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.image', verbose_name='Cover Image'),
        ),
    ]
