version: '1'

services:
  server:
    container_name: ninja-converter-server
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      server/app/env/.env
    tty: true

  client:
    container_name: ninja-converter-client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/client
    ports:
      - 3000:3000
    env_file:
      client/env/.env
    depends_on:
      - server
    tty: true

  nginx:
    image: nginx:latest
    container_name: ninja-converter-nginx
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - client:/var/www/client
    depends_on:
      - server
      - client

volumes:
  client: